[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "-Zshare-generics=y", "-Csplit-debuginfo=unpacked"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
split-debuginfo = "unpacked"